SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS study_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  duration INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
