AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

plugins:
  - rubocop-performance

Style/Documentation:
  Enabled: false

Naming/MethodName:
  AllowedPatterns:
    - "^do_[A-Z_]+$"

Naming/MethodParameterName:
  MinNameLength: 2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 3

Style/CollectionMethods:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Lambda:
  EnforcedStyle: literal

Style/RedundantReturn:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 35
Metrics/ClassLength:
  Max: 120