AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

plugins:
  - rubocop-performance

Style/Documentation:
  Enabled: false

Naming/MethodName:
  AllowedPatterns:
    - "^do_[A-Z_]+$"

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 35