version: '3.9'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password  
    ports:
      - "3306:3306"
    volumes:
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql